

## Java异常继承体系

+ Throwable
	+ Error:致命异常，程序无法处理，如OutOfMemoryError
	+ Exception
		+ checked:受检异常，
		+ unchecked:RuntimeException,不需要显式catch
			
Exception 分为：checked和unchecked


### try-catch


如果finally 是在执行完return之后，这时return 的值是被暂存了的；

```java {.line-numbers}

 public int finallyNotWork(){
        int temp=100;
        try{
            throw new Exception("a exp");
        }catch (Exception e){
            // 返回值被暂存
            return temp;
        }finally {
            // 这里影响不到返回值
            temp=1;
        }
    }
    //方法的返回值为100
```





### 千万不要在finally里return


```java

    static int a=1;
    static int b=10;
    static int c=100;
    @Test
    public void finallyReturnTest(){

        System.out.println(finallyReturn());
        System.out.println("a:"+a);
        System.out.println("b:"+b);
        System.out.println("c:"+c);
    }
    public static int finallyReturn(){
        try{
            //do something
            return ++a;
        }catch (Exception e){
            return ++b;
        }finally {
            return ++c;
        }
    }
```


如果没抛异常，a=2,b=10,c=101,路径a-c
如果a抛异常,a=1,b=11,c=101
这里根本的原因是开发者用finally 写了业务逻辑；




## 异常原理



> If no such exception handler is found in the current method, the current method invocation completes abruptly (§2.6.5). On abrupt completion, the operand stack and local variables of the current method invocation are discarded, and its frame
is popped, reinstating the frame of the invoking method. The exception is then ...
Java 虚拟机标准1.8


1. 如果当前方法没有 此类异常的handler，当前方法中断。
2. 当中断完成，当前帧的操作数栈，局部变量表 被销毁，此方法对应的frame pop 出栈。（参考JVM模型）
3. 在栈顶方法重新抛出异常
4. 如果到异常链的顶端依然没能handle住，抛异常的线程终止运行（terminated）；





在编译时已经确定了异常的handler方式。在class 文件中，每个方法的exception handlers 都存在一张表里。运行时，当抛出一个异常，JVM在这个表里搜索异常handler。



### class文件中的定义：


对于每一个方法，对应的代码有code属性。

```cpp

Code_attribute {
    u2 attribute_name_index;
    u4 attribute_length;
    u2 max_stack;   // 最大的 操作数栈大小
    u2 max_locals;  // 最大本地变量大小
    u4 code_length; //代码长度
    u1 code[code_length];
    u2 exception_table_length;
    { 
        u2 start_pc;    // 异常handler区间 [start_pc, end_pc)
        u2 end_pc;      
        u2 handler_pc;  // 指向异常处理代码开始指令
        u2 catch_type;  // 指向常量池的一个CONSTANT_Class_info，表示catch的类型 
    } exception_table[exception_table_length];
    u2 attributes_count;
    /**
     * 每一个都是一个attribute_info
     *
     */
    attribute_info attributes[attributes_count];
}
```



> end_pc 不包含其实是一个bug。假如是包含的。如果一个方法的代码长度达到最长65535 bytes。最后一个指令时一byte的，那么最后一个指令将无法被handle住。